### ISSUE TITLE
Error running autocrop script

### ISSUE THREAD

**Issue by elias-copin** [agclark12/autocrop_black_edges#2] opened 2023-02-17 11:06 UTC
Hi Andrew, 

I am trying to apply your script to a stack of images I have registered, however I am running into the following error: 

[ERROR] Traceback (most recent call last):
  File "Autocrop_Black_Edges.py", line 124, in <module>
  File "Autocrop_Black_Edges.py", line 119, in main
	at ij.process.FloatProcessor.downsize1D(FloatProcessor.java:987)
	at ij.process.FloatProcessor.downsize(FloatProcessor.java:960)
	at ij.process.ImageProcessor.resize(ImageProcessor.java:2280)
	at ij.plugin.Scaler.createNewStack(Scaler.java:127)
	at ij.plugin.Scaler.resize(Scaler.java:100)
	at ij.ImagePlus.resize(ImagePlus.java:2510)
	at ij.ImagePlus.resize(ImagePlus.java:2502)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
java.lang.ArrayIndexOutOfBoundsException: java.lang.ArrayIndexOutOfBoundsException: 0

	at org.python.core.Py.JavaError(Py.java:547)
	at org.python.core.Py.JavaError(Py.java:538)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:192)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:208)
	at org.python.core.PyObject.__call__(PyObject.java:512)
	at org.python.core.PyObject.__call__(PyObject.java:517)
	at org.python.core.PyMethod.__call__(PyMethod.java:171)
	at org.python.pycode._pyx0.main$4(Autocrop_Black_Edges.py:121)
	at org.python.pycode._pyx0.call_function(Autocrop_Black_Edges.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:119)
	at org.python.core.PyFunction.__call__(PyFunction.java:406)
	at org.python.pycode._pyx0.f$0(Autocrop_Black_Edges.py:124)
	at org.python.pycode._pyx0.call_function(Autocrop_Black_Edges.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1687)
	at org.python.core.__builtin__.eval(__builtin__.java:497)
	at org.python.core.__builtin__.eval(__builtin__.java:501)
	at org.python.util.PythonInterpreter.eval(PythonInterpreter.java:255)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:57)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:31)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.scijava.script.ScriptModule.run(ScriptModule.java:164)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:163)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at ij.process.FloatProcessor.downsize1D(FloatProcessor.java:987)
	at ij.process.FloatProcessor.downsize(FloatProcessor.java:960)
	at ij.process.ImageProcessor.resize(ImageProcessor.java:2280)
	at ij.plugin.Scaler.createNewStack(Scaler.java:127)
	at ij.plugin.Scaler.resize(Scaler.java:100)
	at ij.ImagePlus.resize(ImagePlus.java:2510)
	at ij.ImagePlus.resize(ImagePlus.java:2502)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:190)
	... 29 more

I have run it successfully on the sample image provided. I also seem to be able to run it when I crop my stack, or when my stack is reduced in number of slices. Do you have any idea what may be going wrong? Happy to share images with you if that helps.

**Comment by agclark12** [comment] 2023-02-17 11:19
Hi Elias,

Sorry to hear you are having  trouble with this. It would be great if you could send me an image stack where it doesn't work as well as the cropped version that does work. Then I can try to see what the problem is. Earliest I will have time to have a look would be middle of next week.

**Comment by elias-copin** [comment] 2023-02-17 11:45
DAPI_stack_aligned.tif
<https://drive.google.com/file/d/1RSm9c0qHr0G1bTG3LkgyFa348xCHYR1F/view?usp=drive_web>
 DAPI_stack_cropped.tif
<https://drive.google.com/file/d/1trNOeeztiFGrNWnaN1zl02lnRh3ShNgM/view?usp=drive_web>

Dear Andrew,

Many thanks for your reply - I have attached two image stacks, one of which
is a cropped version of the other. The script seems to run fine on the
cropped version attached, but not the complete image. Thanks again for the
help!

Best regards,
Elias

**Comment by agclark12** [comment] 2023-02-23 14:56
Hi Elias,

Seems like this was somehow related to dealing with this option to have white objects on a black background for binary images, which was not well accounted for previously. I have now fixed this and it seems to work fine now for both of the images you sent. Thanks for the bug report. Let me know if you run into any trouble on your other images. I will close this issue now.

best,
Andrew

**Closed as completed by agclark12** 2023-02-23 14:56 UTC
